name: npm publish

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          cache: npm
      - run: npm install

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          cache: npm
      - run: npm install
      - run: npm run lint

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          cache: npm
      - run: npm install
      - run: npm run build:tracker
      - run: npm run build:router
      - run: npm run test:ci
      - uses: actions/upload-artifact@v2
        with:
          name: tests-coverage
          path: coverage/
          if-no-files-found: error
      - uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: ./coverage/tracker/lcov.info
          parallel: true
          flag-name: tracker
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: ./coverage/router/lcov.info
          parallel: true
          flag-name: router
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: coverallsapp/github-action@1.1.3
        with:
          parallel-finished: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          cache: npm
      - run: npm install
      - run: npm run build:prod:tracker
      - run: npm run build:prod:router
      - uses: actions/upload-artifact@v2
        with:
          name: dist-prod
          path: dist-prod
          if-no-files-found: error
      - run: npm run semantic-release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
